# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Podcast Example
email: na
description: > # this means to ignore newlines until "baseurl:"
  Podcasts with github
baseurl: "/podcast-example"
url: "https://dmnfarrell.github.io"
twitter_username: myname
github_username:  unknown
permalink: /:title.html
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
